FROM apache/airflow:2.7.2-python3.10

USER root

RUN apt-get update && \
    apt-get install -y default-jre net-tools lsof vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y procps

USER airflow

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $PATH:$JAVA_HOME/bin

RUN pip install pyspark==3.4.4
RUN pip install cassandra-driver
RUN pip install plotly